name: Incorrect suggestion
description: Report incorrect suggestions
title: Incorrect suggestion
labels: ["suggestions"]
body:
  - type: textarea
    id: word
    attributes:
      label: Word(s)
      description: Which words were mistakenly highlighted?
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: URL
      description: What URL were you checking?
      placeholder: https://example.com
